Fix linter config
hexlet-rus/runit pull request #300
Opened 2023-07-07 09:27 UTC by faciledictu

Add --fix option to lint command
Добавляет опцию --fix в команду lint в Makefile в директории frontend. Теперь при запуске make lint проблемы по возможности будут исправляться не только в файлах бэкенда, но и на фронтенде

Allow js and jsx files checking
Включает подсветку проблем ts-check для файлов фронтенда

Fix code formatting
Применяет make lint, исправлет проблемы форматирования во всех файлах проекта. Затрагивает ряд файлов бэкенда

2023-07-10 08:36 UTC, fey requested changes

2023-07-10 08:36 UTC, fey commented on frontend/Makefile
> +	npx eslint --ext .jsx,.js ./ --fix
Команда линт должна только проверять/сообщать об ошибках.
Ибо она запускается перед пушем/коммитом и на CI.
Добавьте отдельную команду `make lint-fix`, которая будет фиксить замечания линтера.

2023-07-11 12:02 UTC, ola-9 commented on frontend/Makefile
> +	npx eslint --ext .jsx,.js ./ --fix
Тоже самое нужно сделать и для backend, то есть добвить отдельную команду. Сейчас на пуш запускается команда `make lint`, которая в свою очередь запускает `make lint-frontend` & `make lint-backend`, а [lint-backend](https://github.com/hexlet-rus/runit/blob/7f29ea560a463f8713166bb0c5ae7ec53e0dfff1/backend/package.json#L14) запускается с опцией --fix.

2023-07-12 16:28 UTC, faciledictu commented
1. Из команд вызовы линтера, назначенных на `make lint`, `make lint-frontend` `make-lint-backend`, убран флаг `--fix`, теперь они только выводят ошибки.
2. Добавил команды `make lint-fix`, `make lint-frontend-fix` `make-lint-backend-fix`, которые служат для исправления ошибок (вызывают линтер с флагом `--fix`).

2023-07-12 17:10 UTC, merged