Language detector
hexlet-rus/runit pull request #356
Opened 2023-08-18 13:23 UTC by shahzod418

2023-08-18 13:25 UTC, shahzod418 commented
#354

2023-08-18 17:35 UTC, fey commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
А для чего эта проверка?

2023-08-19 09:43 UTC, shahzod418 commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
Данная проверка была нужна для того, чтобы в `development` режиме работал выбор `dev` языка (отображаются только ключи i18next).

Так же у меня возникли проблемы с тестами. Они все, кроме `has title` падали с ошибкой `Timed out` при использовании `LanguageDetector`

2023-08-19 09:51 UTC, shahzod418 commented
Буду ждать сливания в main данных PR:
#358
#339

2023-08-19 11:49 UTC, fey commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
Не совсем понимаю, а зачем нам dev язык?
Обычно если работает детект, то он или работает или нет. Обычно такое делают через какой-нибудь конфиг и переменную окружения. 
Т.е. в конфиге получаем переменную окружения и дальше в приложении проверяем должны ли мы детектить локаль и ставить нужную локаль.

2023-08-19 12:02 UTC, shahzod418 commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
Он просто был, вот я и оставил возможность его выбрать)

Хотя я бы предпочел его убрать и добавить debug в development окружении

2023-08-19 12:11 UTC, fey commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
все равно не понимаю :thinking: @dzencot посмотри, пожалуйста ПР.

Я бы сделал отдельную переменную окружения, которую обозвал бы нужным образом. Это удобнее, чем зависеть от окружения (прод/дев)

2023-08-19 12:15 UTC, shahzod418 commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
<img width="517" alt="Снимок экрана 2023-08-19 в 15 14 54" src="https://github.com/hexlet-rus/runit/assets/88596835/a565fd73-1ac4-4031-b08c-57960638cb8f">

Я об этом

2023-08-19 12:29 UTC, fey commented
И задеплойте пожалуйста демку на render

2023-08-19 12:41 UTC, shahzod418 commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
А я поэтому и написал что жду merge двух PR, чтобы потом обернуть все в switch.

Получится так:
- **production**: Добавляется `LanguageDetector` и `fallbackLanguage`
- **development**: Добавляется `LanguageDetector`
- **test**: Добавляется `lng`

Почему так:

Если у нас есть `lng`, то плагин `LanguageDetector` становится бесполезным, так как всегда будет выбираться `lng`. А наличие `fallbackLanguage` не позволит выбрать `dev`, даже если он будет указан в `supportedLngs`.
При наличии плагина`LanguageDetector` не проходят тесты, попробую решить эту проблему. Если не получится, то в тестах плагин добавляться не будет

2023-08-19 15:52 UTC, faciledictu commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
Я думаю, «язык» dev – вообще не самая важная штука в при разработке. Я делал для удобства, когда менял структуру файлов с локалями и надо было переключать, чтобы смотреть откуда какое сообщение берется, но потом он там так и остался. Можно смело убрать.

2023-08-19 16:11 UTC, shahzod418 commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
Уберу

2023-08-21 10:58 UTC, shahzod418 commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
`debug: true`
В консоли будет объект resources

2023-08-21 10:59 UTC, fey commented on frontend/src/application.jsx
> +      ...(process.env.NODE_ENV !== 'development' && {
ага, тогда нам это будет норм.

2023-08-24 19:15 UTC, shahzod418 commented
Я бы хотел дождаться test в NODE_ENV, чтобы не пришлось добавлять переменную в playwright config.

Выбранный язык записывается в local storage

2023-09-01 15:25 UTC, faciledictu commented
@shahzod418 Боюсь, тот ПР подвис пока. Может, выложить пока так, сделав дефолтный язык в development-окружении русским, чтобы тесты не валились?

2023-09-01 15:31 UTC, shahzod418 commented
@faciledictu Нужно сделать deploy на render?

2023-09-01 15:38 UTC, shahzod418 commented
Если что вот)
https://shahzod418-runit.onrender.com/

2023-09-03 15:12 UTC, dzencot requested changes

2023-09-03 15:12 UTC, dzencot commented on frontend/src/application.jsx
> +  initI18next();
Тут предлагаю добавить `await`, чтобы гарантированно выполнять промис в функции.

2023-09-03 16:48 UTC, shahzod418 commented
@dzencot добавил

2023-09-08 13:04 UTC, fey commented
@dzencot посмотри плз пр

2023-09-08 13:06 UTC, dzencot approved these changes

2023-09-08 14:32 UTC, fey commented
@shahzod418 можете создать ищщус с задачей дописать тесты для детекта локалей?

2023-09-08 14:40 UTC, dzencot commented
Этот пр можно мержить?

2023-09-09 07:55 UTC, shahzod418 commented
Можно

2023-09-11 08:54 UTC, merged