Separate the title from the description
hexlet-rus/runit pull request #452
Opened 2024-04-04 08:00 UTC by IVANn84

According to Issues 440, the headings are separated from the description in the help section.   P/S: I automatically started the linter after the changes I made and it automatically corrected some more files.. Is it really not very good?.. I looked at the diff, there seem to be only cosmetic changes.

2024-04-04 14:50 UTC, fey requested changes

2024-04-04 14:50 UTC, fey commented on frontend/src/pages/about/Faq.jsx
> +            {convertToHtml(t('faq.a23'), t('faq.a24'))}
@IVANn84 у вас в итоге получилось, что строка разделилась на две части. Я имел ввиду, что у вас имеено сам тег strong будет внутри строки-локализации. Т.е. a23 будет в одном ключе с a24. Ладно, раз решили делать так, то давайте ревьювить +)

2024-04-04 14:50 UTC, fey commented on frontend/src/pages/about/Faq.jsx
> +  function convertToHtml(header, text) {
Имя функции не говорит о том, что мы делаем. Какая именно конвертация? Непонятно. Внутри может что угодно конвертироваться в html, а по факту здесь возвращается две строки - одна ссылкой (кстати почему? Никакой ссылки жеж здесь нет), другая выделенный текст.

2024-04-04 14:50 UTC, fey commented on frontend/src/locales/ru.json
> +    "a111": " IDE повышают производительность труда программистов, выполняя повторяющиеся задачи разработки, которые обычно являются частью каждого изменения кода",
вот чего я боялся - появился пробел, который надо учитывать. Здесь проще сделать что-то типа
```
    "a110": "<strong>Автоматизация локальной сборки</strong>  IDE повышают производительность труда программистов, выполняя повторяющиеся задачи разработки, которые обычно являются частью каждого изменения кода",
    ```
    
    тогда вы это просто как html рендерите. Мб во фреймворке можно посмотреть список разрешенных тегов. Например таким образом выводятся форматированные тексты в Хекслете, когда нужны например формулы

2024-04-05 10:30 UTC, IVANn84 commented on frontend/src/locales/ru.json
> +    "a111": " IDE повышают производительность труда программистов, выполняя повторяющиеся задачи разработки, которые обычно являются частью каждого изменения кода",
Спасибо за разбор!
"a110": "<strong>Автоматизация локальной сборки</strong>  IDE повышают производительность труда... 
я видел такой пример, но так и не догадался как задать html  в качестве значения ключа. Попробую поискать еще какое нибудь решение.

2024-04-06 07:26 UTC, IVANn84 commented on frontend/src/locales/ru.json
> +    "a111": " IDE повышают производительность труда программистов, выполняя повторяющиеся задачи разработки, которые обычно являются частью каждого изменения кода",
Здравствуйте, исправил замечания , согласно статье Hexlet перезаписал предыдущий PR , но теперь никак не могу понять отправились ли Вам изменения или нет..( . Подскажите пожалуста пришел ли новый PR. спасибо

2024-04-06 07:27 UTC, IVANn84 commented
Здравствуйте, исправил замечания , согласно статье Hexlet перезаписал предыдущий PR , но теперь никак не могу понять отправились ли Вам изменения или нет..( . Подскажите пожалуста пришел ли новый PR. спасибо

2024-04-08 09:53 UTC, fey commented
Да, вроде отправились =)

2024-04-08 12:46 UTC, merged