Close #449
hexlet-rus/runit pull request #481
Opened 2024-05-06 16:42 UTC by bobronaud

Демо - https://bobronaud-runit.onrender.com

2024-05-06 16:52 UTC, fey commented
Уже есть ПРчик https://github.com/hexlet-rus/runit/pull/467

Предлагаю подождать @Heaven-Tonight с фиксом линтера.

2024-05-06 16:58 UTC, bobronaud commented
О как
А я смотрю, ишьюс месяц без движения, решил взять

2024-05-06 18:06 UTC, Heaven-Tonight commented
@fey, кажется это решение работает корректно и оно, на мой взгляд, по-лучше моего, можно его тогда замерджить.

А я что-то прошляпила момент с воркфлоу, в следующий раз внимательнее  буду) Еще и БД на Рендере пала смертью храбрых)

2024-05-07 08:04 UTC, fey commented
ок, тогда поревьювим этот ПР

2024-05-20 13:23 UTC, dzencot requested changes

2024-05-20 13:23 UTC, dzencot commented on frontend/src/components/Forms/SignInForm.jsx
> +        localStorage.removeItem('guestUserData');
Предлагаю перенести это в `auth.signIn()`

2024-05-20 19:07 UTC, bobronaud commented
внёс изменения
только я немного в гите запутался, все норм с ПРом?

2024-05-20 19:30 UTC, bobronaud commented
кажется, я все исправил

2024-06-04 13:01 UTC, fey commented
Задеплойте демку плз

2024-06-20 12:04 UTC, fey commented
@bobronaud тыц) Тут есть лишнее в ПРе

2024-08-26 07:44 UTC, merged