[#456] Feat: delete one or more snippets
hexlet-rus/runit pull request #507
Opened 2024-06-15 13:42 UTC by vyacheslav-pv

[#456] Реализован функционал удаления нескольких сниппетов путем отметки чекбоксов.

Демо https://vyacheslav-pv-runit.onrender.com

2024-06-16 18:32 UTC, bobrov-site commented
Работает кайфово. Класс!

2024-06-17 16:05 UTC, fey commented
![image](https://github.com/hexlet-rus/runit/assets/697178/ba71cf2d-ad40-4b06-a8ad-5313870dbcf7)


1) После снятия галочки с чекбокса, он не возвращается назад на иконку языка.
2) Почему меняется именно иконка языка?)
3) Давайте сделаем так - сверху добавляем бар для кнопок упражения (под именем юзера), там будет режим "выбрать" который вклчюает отображение чекбоксов. Логика похожа на то, как мы выбираем фото на телефоне. Ну и иконку языка не трогаем. Лучше заменить карандаш, ведь мы все равно находимся в "режиме выбора" и он нам ни к чему.

2024-06-18 13:30 UTC, vyacheslav-pv commented
> 1. После снятия галочки с чекбокса, он не возвращается назад на иконку языка.
> 2. Почему меняется именно иконка языка?)
> 3. Давайте сделаем так - сверху добавляем бар для кнопок упражения (под именем юзера), там будет режим "выбрать" который вклчюает отображение чекбоксов. Логика похожа на то, как мы выбираем фото на телефоне. Ну и иконку языка не трогаем. Лучше заменить карандаш, ведь мы все равно находимся в "режиме выбора" и он нам ни к чему.

Приветствую!
1 и 2 пункты - изначально так и было задумано, сделал по аналогии сервиса replit
3. Давайте попробую. 
Хотелось бы уточнение, в баре будет только пункт "выбрать", и после отметки чекбоксов появляется плашка "удалить" (как сейчас реализовано). Или делаем в баре еще пункт удалить, который изначально неактивный, активируется после отметки чекбоксов, пример выпадающее меню
![Скриншот 18-06-2024 154326](https://github.com/hexlet-rus/runit/assets/111936841/50fb951a-2d63-4e71-ac77-67fe70d8cfe0)

2024-06-18 13:33 UTC, fey commented
Не совсем понял, можете пример показать, как это может быть выглядеть?

Идея в том, что вы можете выбрать несколько сниппетов и что-то с ними сделать, например удалить, переместить в "папку" и тд. Но пока только удаление.

2024-06-18 16:35 UTC, vyacheslav-pv commented
@fey думаю, как лучше.
Под именем юзера кнопка: выбрать сниппеты и кнопку удалить, пример 
![Скриншот 18-06-2024 230752](https://github.com/hexlet-rus/runit/assets/111936841/4c60106b-7de1-42ee-9c81-04509d3b170a)
Но наверное будет лучше, если после нажатия кнопки выбрать и отметки одного или нескольких чекбоксов - появляется кнопки с действиями (удалить, и т.д.)

2024-06-20 12:06 UTC, fey commented
@vyacheslav-pv смотрите, кнопка выбора отвечает олько за переход в режим селекта. Т.е. на сниппетах появляется чекбокс
Дальше вы выбираете сниппеты и что-то с ними делаете, уже отдельные кнопки отвечают за отправку, удаление и тд. Лучше делать в виде кнопок, тк это же действия (просто вижу, что у вас это ссылки). Под именем юзера норм

2024-07-05 10:29 UTC, vyacheslav-pv commented
Доработал функционал, демо https://vyacheslav-pv-runit.onrender.com
Появилась возможность с помощью кнопки отображать/скрывать чекбоксы.
А также доработан тулбар для выбранных сниппетов, он "прилипает" снизу блока сниппетов, удобно при скроллинге. 
В тулбаре для отмеченных сниппетов доступны кнопка "удалить" и добавлена кнопка "отмена".
![Скриншот 05-07-2024 165735](https://github.com/hexlet-rus/runit/assets/111936841/8a4e4db1-f8a7-45f3-a430-2718877f6580)
![Скриншот 05-07-2024 165847](https://github.com/hexlet-rus/runit/assets/111936841/14036332-517a-4357-9c16-63cc30b8fd0d)

2024-07-11 08:00 UTC, HelenOne commented
@vyacheslav-pv это итоговая версия? Можно проверять?

2024-07-11 10:38 UTC, vyacheslav-pv commented
> @vyacheslav-pv это итоговая версия? Можно проверять?

@HelenOne Привет. да, посмотрите пожалуйста.

2024-07-21 14:27 UTC, dzencot requested changes

2024-07-21 14:27 UTC, dzencot commented on frontend/src/components/Modals/DeleteSnippetModal.jsx
> +    snippetsSlice.forEach(async (snippet) => {
Тут несколько замечаний:
* `snippetsSlice` — такое имя лучше заменить, иначе путаница с `snippetsSlice.js`
* Нам не нужно в цикле делать проход по всем снипетам. Лучше отфильтровывать список и дальше с ним работать. Лучше доработать `snippetApi`, чтобы можно было передать список снипетов для удаления. В будущем мы можем доработать бэк, чтобы он удалял списками. Можно даже доработать `deleteSnippet`, чтобы он умел работать со списками или id одного снипета.

2024-07-21 14:27 UTC, dzencot commented on frontend/src/slices/snippetsSlice.js
> +  isCheckboxesOpen: false,
Тут получается смешение данных и ui-состояния. По идее в этом слайсе данные, которые приходят с бэкенда. По-хорошему они еще могут быть синхронизированы с бэкендом. А вот выделен ли снипет — это уже состояние интерфейса. Сам по себе от этого снипет не меняется. Поэтому лучше не добавлять к нему поле `checked`. Предлагаю выделить слайс для состояния ui приложения. В нем можно хранить коллекцию выделенных снипетов.

2024-10-18 08:39 UTC, dzencot commented
Чет пр завис(

2024-10-20 09:46 UTC, vyacheslav-pv commented
> Чет пр завис(

Привет. на днях отправлю pr

2024-11-12 08:31 UTC, merged