[#530]: Profile avatar is now either Github profile picture, or capitalized first letter of username
hexlet-rus/runit pull request #534
Opened 2024-07-24 15:30 UTC by Mehdi-Messaadi

If the user signs in with **Github**, their profile avatar will automatically become their **GitHub profile picture**, like this screenshot below:

![github profile picture](https://github.com/user-attachments/assets/ce081bd6-0449-45bb-a8bc-5a54cddfb14d)

Otherwise, if the user signed in traditionally, then the first **letter of their username** will be **capitalized** and used as avatar to enhance UX, as show in the screenshot below:

![No github](https://github.com/user-attachments/assets/94e06942-6766-4f1a-9452-53cdbc758910)

2024-07-25 04:53 UTC, sergiozeppo requested changes
Hi, Mehdi! 
Good work! This is exactly what I talked about! 
You need to fix some lint and prettier errors in your solution

2024-07-25 04:53 UTC, sergiozeppo commented on frontend/src/components/Avatar/index.jsx
> +          textAnchor="middle"
Move up textAnchor prop above ```x``` and ```y```

2024-07-25 04:53 UTC, sergiozeppo commented on frontend/src/components/Navigation/UserMenu.jsx
> +  //This function takes the first letter of the username and converts it to uppercase
Add a whitespace between // construction and text of comment

2024-07-25 04:53 UTC, sergiozeppo commented on frontend/src/components/Navigation/UserMenu.jsx
> +  }
Add ```;```

2024-07-25 09:00 UTC, fey commented
Hi, thanks for participating! Please see the tests, what needs to be fixed.
Let's create an issue for the backend, so that we get a URL with a picture from the backend, and if there is no picture, there would be some kind of stub

2024-07-25 14:24 UTC, Mehdi-Messaadi commented
Hi @sergiozeppo!
Thanks a lot for the remarks. I believe they're all fixed now.

2024-07-25 16:51 UTC, dzencot commented
Hi! It has one problem: the username can be occupied by another user. Anyone can enter any username. So, we need to add this feature to the backend.

2024-07-26 04:34 UTC, sergiozeppo commented
> Hi! It has one problem: the username can be occupied by another user. Anyone can enter any username. So, we need to add this feature to the backend.

Hi @dzencot ! The problem is really is, but I don't think that it's related both to this issue or PR. 
This is a separate issue, I think.

2025-05-12 12:32 UTC, closed without merging